import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
export const abcdFont = localFont({
  src: [
    {
      path: "./fonts/ABCDiatypeRoundedVariable-Trial.ttf",
      weight: "100 900",
      style: "normal",
    },
  ],
  variable: "--font-diatype",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${abcdFont.variable} antialiased`}>{children}</body>
    </html>
  );
}
